var canvasBackground = './resources/back.png';
var itemList = [
    {
        name: 'bottle',
        top:  25,
        left: 25,
        height: 50,
        width:50,
        imgUrl: './resources/bottle - coloured.png',
    },
    {
        name: 'charger',
        top:  25,
        left: 125,
        height: 50,
        width: 50,
        imgUrl: './resources/charger-158460.png',
    },
    {
        name: 'chocolate',
        top:  25,
        left: 225,
        height: 50,
        width: 50,
        imgUrl: './resources/chocolate-chip-cookies.png',
    },
    {
        name: 'earphones',
        top:  25,
        left: 325,
        height: 50,
        width: 50,
        imgUrl: './resources/earphones.png',
    },
    {
        name: 'napkin',
        top:  25,
        left: 425,
        height: 50,
        width: 50,
        imgUrl: './resources/napkin-box-312693.png',
    },
    {
        name: 'pillows',
        top:  25,
        left: 525,
        height: 50,
        width: 50,
        imgUrl: './resources/pillows-29866.png',
    },
    {
        name: 'sandwitch',
        top:  25,
        left: 625,
        height: 50,
        width: 50,
        imgUrl: './resources/sandwich-148023.png',
    },
    {
        name: 'socks',
        top:  25,
        left: 725,
        height: 50,
        width: 50,
        imgUrl: './resources/socks-306802.png',
    },
]

var positionList = [
    {
        name: 'left-1',
        top:  100,
        left: 50,
        height: 125,
        width:100,
    },
    {
        name: 'left-2',
        top:  100,
        left: 150,
        height: 125,
        width:100,
    },
    {
        name: 'left-3',
        top:  225,
        left: 50,
        height: 125,
        width:100,
    },
    {
        name: 'left-4',
        top:  225,
        left: 150,
        height: 125,
        width:100,
    },
    {
        name: 'right-1',
        top:  100,
        left: 550,
        height: 125,
        width:100,
    },
    {
        name: 'right-2',
        top:  225,
        left: 550,
        height: 125,
        width:100,
    },
    {
        name: 'right-3',
        top:  100,
        left: 650,
        height: 125,
        width:100,
    },
    {
        name: 'right-4',
        top:  225,
        left: 650,
        height: 125,
        width:100,
    },
    
]
